### ISSUE TITLE
Multiple input tools in same phase "share" content

### ISSUE THREAD

**Issue by jakob-sikken** [graasp/graasp-desktop#136]
If you place two input tools in the same phase, the saved content of the first input is also shown in the second input after reloading.
It seems that the handling on which window/iframe a storage callback should be done is failing.
This is happens also when multiple twente tools are placed in the same phase, callbacks are sometimes applied at the wrong instance.

**Comment by juancarlosfarah** [comment]
Thanks for reporting this. I have been able to reproduce. Looking into possible solutions.

**Comment by juancarlosfarah** [comment]
@jakob-sikken, this has been fixed in v0.11.1. Kindly let me know if it works for you. Thanks!

**Comment by jakob-sikken** [comment]
I am still getting some warnings that a "reply" is delivered at the wrong iframe. But now all twente apps are at least starting up.
And in case of a phase with two input boxes, the second input box still shows the same content as the first input box.

**Comment by juancarlosfarah** [comment]
@jakob-sikken, you are right. For me it's working intermittently (as shown below), which means that there is something that is not consistently working as expected. Will reopen and look into it.

![image](https://user-images.githubusercontent.com/1707188/61596260-9bf66000-abc6-11e9-99d1-67924026f291.png)

**Comment by juancarlosfarah** [comment]
@jakob-sikken, we have released another fix in v0.11.2. Please let us know if that works for you. Thanks!

https://github.com/graasp/graasp-desktop/releases/tag/v0.11.2

**Comment by jakob-sikken** [comment]
I don't see any changes. The problems are still there.

**Comment by juancarlosfarah** [comment]
@jakob-sikken, thanks for reporting. I'm indeed seeing the intermittent issue again for resources. However, for the configuration (e.g. header / no header), it seems to be working fine. Can you confirm that if you have two input boxes with different configs they indeed load differently?

**Comment by jakob-sikken** [comment]
Yes, the configurations are loaded by the correct instance.

**Comment by juancarlosfarah** [comment]
@jakob-sikken, thanks for your response. I believe that the problem is now at the level of the input app. I'm addressing this here:

https://github.com/graasp/graasp-app-input/issues/20

**Comment by juancarlosfarah** [comment]
@jakob-sikken, I did some more digging and indeed there is a concurrency issue with some channels in the desktop application, so I will reopen this issue and address this.

**Comment by juancarlosfarah** [comment]
@jakob-sikken, I made another change and released v0.11.3. Kindly check if it solves the problems you were seeing.

https://github.com/graasp/graasp-desktop/releases/tag/v0.11.3

**Comment by jakob-sikken** [comment]
It seems that most problems are solved. However at start-up a few warnings from our tools, about receiving an unexpected message. But I have difficulty repeating them. I made you owner of the ILS that I use for testing.
